export const hangeul = {
  consonants: [
    { id: 1, char: 'ㄱ', name: 'giyeok' },
    { id: 2, char: 'ㄴ', name: 'nieun' },
    { id: 3, char: 'ㄷ', name: 'digeut' },
    { id: 4, char: 'ㄹ', name: 'rieul' },
    { id: 5, char: 'ㅁ', name: 'mieum' },
    { id: 6, char: 'ㅂ', name: 'bieup' },
    { id: 7, char: 'ㅅ', name: 'siot' },
    { id: 8, char: 'ㅇ', name: 'ieung' },
    { id: 9, char: 'ㅈ', name: 'jieut' },
    { id: 10, char: 'ㅊ', name: 'cheiut' },
    { id: 11, char: 'ㅋ', name: 'kieuk' },
    { id: 12, char: 'ㅌ', name: 'tieut' },
    { id: 13, char: 'ㅍ', name: 'pieup' },
    { id: 14, char: 'ㅎ', name: 'hieut' },
    { id: 15, char: 'ㄲ', name: 'ssang giyeok' },
    { id: 16, char: 'ㄸ', name: 'ssang digeut' },
    { id: 17, char: 'ㅃ', name: 'ssang bieup' },
    { id: 18, char: 'ㅆ', name: 'ssang shiot' },
    { id: 19, char: 'ㅉ', name: 'ssang jieut' },
  ],
  vowels: [
    { id: 1, char: 'ㅏ', name: 'a' },
    { id: 2, char: 'ㅑ', name: 'ya' },
    { id: 3, char: 'ㅓ', name: 'eo' },
    { id: 4, char: 'ㅕ', name: 'yeo' },
    { id: 5, char: 'ㅗ', name: 'o' },
    { id: 6, char: 'ㅛ', name: 'yo' },
    { id: 7, char: 'ㅜ', name: 'u' },
    { id: 8, char: 'ㅠ', name: 'yu' },
    { id: 9, char: 'ㅡ', name: 'eu' },
    { id: 10, char: 'ㅣ', name: 'i' },
    { id: 11, char: 'ㅔ', name: 'e' },
    { id: 12, char: 'ᅢ', name: 'ae' },
    { id: 13, char: 'ㅖ', name: 'ye' },
    { id: 14, char: 'ㅒ', name: 'yae' },
    { id: 15, char: 'ᅪ', name: 'wa' },
    { id: 16, char: 'ᅯ', name: 'wo' },
    { id: 17, char: 'ᅫ', name: 'wae' },
    { id: 18, char: 'ᅰ ', name: 'we' },
    { id: 19, char: 'ᅬ', name: 'oe' },
    { id: 20, char: 'ᅱ', name: 'wi' },
    { id: 21, char: 'ᅴ', name: 'ui' },
  ]
}
